### ISSUE TITLE
Issues when running games off of SD card

### ISSUE THREAD

**Issue by TheMCNerd2017** [Robz8/TWLoader#143]
Basically, whenever I try to load games off of the microSD card, they hang at a white screen and do not do anything. Only a few games do load up, but they experience very bad lag. An example would be Sonic Rush, which lags incredibly bad(audio also acts weird during these "lag spikes") whenever something new has to load, like text, sprites, sounds, etc.

I have also tried to launch games like Toy Story 3, Super Mario 64 DS, and Pokemon Volt White 2 from the microSD card, but they simply hang at a white screen.

I have no idea what is causing this to happen, as games ran from the game carts themselves work perfectly fine, The microSD in the system is the 4GB one that came with the system when I first got it.

**Comment by deadair3210** [comment]
Running games off of the SD card is still not perfect and is a serious WIP as far as I know.

Don't expect perfect gameplay or speeds

**Comment by Robz8** [comment]
This is currently normal. [nds-bootstrap](https://github.com/ahezard/nds-bootstrap) patches the roms to redirect Slot-1 reads to the SD Card.
Both ARM7 and ARM9 proccessors read the Slot-1 card slot, but since only ARM7 can read the SD Card, loading speeds will be slow, and with it now recently using the DSi WRAM as data transfar+cache, there's improvements.
nds-bootstrap is still being worked on, so more games will be supported, and loading speed will be more improved.

As for Super Mario 64 DS white screening, update bootstrap by pressing X in settings screen, and make sure Lock ARM9 SCFG_EXT is off.

**Comment by maorninja** [comment]
For SM64DS, can you do a few debugging steps for me?

The steps I'm talking about are the steps mentioned at the nds-bootstrap thread talking about debugging SM64DS...

**Comment by TheMCNerd2017** [comment]
OK, what steps do you want me to do _maornija_?

**Comment by TheMCNerd2017** [comment]
Also, I found out that the class of the microSD in my system is a Class 4, which explains why some things are quite slow.

**Comment by GerbilSoft** [comment]
SD class indicates minimum write speed. Class 4 means your card is guaranteed to sustain at least 4 MB/s when writing. It doesn't say anything about minimum read speed or maximum read/write speed.

**Comment by TheMCNerd2017** [comment]
Oh, OK. But when I tested the card manually, the highest write speed I got was around 8 MB/s. Is that a good write speed?

**Comment by maorninja** [comment]
@TheMCNerd2017 

> To access the crash dump screen, crash the game. After doing so...
> Hold L + R + A + Left, then release.
> Hold Down + B, then release.
> Hold Start + Select.
