### ISSUE TITLE
Add Games menu uses 3DS SD rather than the Flashcart SD on Acekard 2i

### ISSUE THREAD

**Issue by RibShark** [Robz8/TWLoader#347]
### Your 3DS

Tell us which console do you have:

- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

- [x]  Boot9Strap (SigHax)
- [ ]  A9LH (Only Sysnand)
- [ ]  A9LH + Emunand
- [x]  Luma3DS
- [ ]  AuReiNAND
- [ ]  Other CFW [specify]
- [ ]  Older CFW
- [ ]  Not using CFW / Using TWLoader in 3DSX format

### Console version

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### TWLoader version

Tell us which versions you are using:

- [x]  Latest release
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release

### Expected behaviour

When Add Games is selected with an Acekard 2i inserted, a list of files on the flashcarts SD card should be displayed.

### Actual behaviour

Rather than the files on the flashcart being displayed, a list of files on the 3DS's SD card are displayed.

### Steps to reproduce

1. Place all necessary files for flashcart ROM loading on the Acekard 2i's SD and the 3DSs SD.
2. Configure TWLoader to load from the Acekard 2i.
3. Select add games. The Acekard 2i will load a file manager with the 3DS SD contents listed.

**Comment by Jolty95** [comment]
Can you show a screenshoot of 3DS SD card, A2i card and TWLoader image with that content please?

**Comment by RibShark** [comment]
Relevant 3DS SD Contents:
````
├───_nds
│   │   GBARunner2.nds
│   │   loadcard_dstt.nds
│   │   old-bootstrap.nds
│   │   release-bootstrap.nds
│   │   unofficial-bootstrap.nds
│   │   nds-bootstrap.ini
│   │   YSMenu.ini
│   │   ntr_forwarder.ini
│   │   
│   └───twloader
│       │   release-bootstrap
│       │   TWLD.twldr
│       │   unofficial-bootstrap
│       │   settings.ini
│       │   
│       ├───cia
│       │       TWLoader - TWLNAND side (part 2).cia
│       │       TWLoader - TWLNAND side.cia
│       │       TWLoader.cia
│       │       
│       ├───loadflashcard
│       │       ace_rpg.nds
│       │       r4.nds
│       │       
│       ├───bnricons
│       │   └───flashcard
│       ├───boxart
│       │   ├───flashcard
│       │   └───slot1
│       └───gamesettings
│           └───flashcard
````

Flashcart SD contents: https://pastebin.com/EzYStqk7

The lens on my phone is broken so I can't take a photo of what happens, but I get the DS-Mode TWLoader with the message "Select a game to add to the flashcard game list." and on the bottom screen, the files on the 3DS's SD card are displayed (rather than those of the Acekard).

**Comment by topher587** [comment]
I'm experiencing the same issue. My first time using twloader is with the current release and a newly formatted SD card in my ackard2i. 

On the latest stable Luma release
Acekard2i with Pippa Funnell Bootloader (Horse Icon)
fat:\ has the contents of DS Game Forwarder Pack Acekard 2i folder (ysmenu, ysmenu_norm, etc) as well as the "all flashcarts" contents TWLoader.7z per instructions in the wiki and on the gbatemp post. 

Acekard2i is selected as the flashcard type within the settings menu. 

When choosing "Add Games", the TWLoader flashcart forwarder app is loaded from the flashcart. However, you are shown the contents of sd:/ (N3DS MicroSD) instead of fat:/ (Acekard2i microsd)

If you have any games on sd:/ you can choose that file, and a forwarder is created with the boxart. 

Launching the forwarder created this way (for a game stored on sd:/) causes ysmenu to load from the flash cart. 

The flashcart's akaio menu can be launched properly from the TWLoader Slot1 menu or from the 3DS b9s/luma home menu. 

If you launch the flashcart from home menu, you can launch twloader.nds and view the contents of fat:/ as expected, but trying to create forwarders fails if performed this way.

**Comment by vampirexxxx** [comment]
I am using Acekard 2 (non (i) version), and I experienced the same issue where once TWLoader it only shows the 3DS card (sd:/)

But I have a found a workaround:

- Downloaded the latest version of akaio, and renam 'ak4menu.nds' to 'YSMenu.nds'
- Replace/rename the 'YSMenu.nds' on the Flashcart SD
- Load 'Add Games' in TWLoader, wait while it boots into the Akaio menu.
- Manually load the _nds/twloader.nds rom.
- Now it should list all files in the flashcart (fat:/)
- Add your games, when your done, rename 'YSMenu.nds' or move it to a backup folder.
- Copy back the original 'YSMenu.nds' and the games should load now.

I guess the problems lies with YSMenu?

Hope this helps others experiencing this issue.

**Comment by Spodi** [comment]
You can manually create an .ini file, if you know the path on your flashcard and the Title ID. But that is extremly tedious to do for alot of roms. 

example: Castlevania - Order of Ecclesia.ini
```
[FLASHCARD-ROM]
NDS_PATH = GAMES/Castlevania - Order of Ecclesia.nds
TID = YR9PA4
```

Direct use of AKAIO wouldn't be a bad sollution, although that would write on SD onevery launch. I don't know

**Comment by Robz8** [comment]
Closing this issue, as AK2i support has been removed.
