### ISSUE TITLE
Error has occured when loading nds games with twloader

### ISSUE THREAD

**Issue by SplatMan333** [Robz8/TWLoader#55]
Hi, when whenever I play my games, Super Mario 64 DS and WarioWare: Touched!, My system says error has occured. This happens when try to launch the games. Plz Help! Thanks!

**Comment by Robz8** [comment]
Try again. It'll happen sometimes.

**Comment by SplatMan333** [comment]
Thanks!

**Comment by Robz8** [comment]
What I meant to say was, did you follow step 3 in the guide?

**Comment by SplatMan333** [comment]
yes

**Comment by Robz8** [comment]
Are you using Luma3DS CFW?

**Comment by SplatMan333** [comment]
No, I'm using ReiNAND Sysnand sig patch on 9.2 New 3DS USA

**Comment by Robz8** [comment]
ReiNAND is an outdated CFW. Switch to Luma3DS, as it fixes the problem.
https://github.com/AuroraWright/Luma3DS/wiki/Installation-and-upgrade#upgrading-from-arn-43-or-older-to-luma3ds

**Comment by Margen67** [comment]
Also switch to A9LH if you haven't already http://3ds.guide/

**Comment by Abastante** [comment]
I have the same issue when trying to load SM64. I'm on Luma3ds on emunand. Any clue what could be happening?

**Comment by Margen67** [comment]
>emunand

Well there's your problem. You need to switch to A9LH SysNAND.

**Comment by Abastante** [comment]
I don't understand. Why would the installation instructions even say the following it it works on A9LH only?

(This step is required. An error screen will appear if this isn't installed.) Install "TWLoader - TWLNAND side.cia" that's in "sdmc:/_nds/twloader/cia/" to SysNAND (also to EmuNAND, if you have EmuNAND).
Install "TWLoader.cia" to whichever NAND you use (SysNAND or EmuNAND).

**Comment by Margen67** [comment]
You need to follow http://3ds.guide/

**Comment by Valeri0p** [comment]
@Robz8 Please disinfect from the troll.
@Abastante Be sure to follow the directions on the FAQ, and considers an update of your environment.

**Comment by pbanj** [comment]
@Valeri0p its not trolling if he's right. Just because you don't like what he is saying doesn't make him a troll.

**Comment by Abastante** [comment]
So there is no way to run this on Emunand? I don't understand why would @Robz8 add "3. (This step is required. An error screen will appear if this isn't installed.) Install "TWLoader - TWLNAND side.cia" that's in "sdmc:/_nds/twloader/cia/" to SysNAND (also to EmuNAND, if you have EmuNAND)." to the installation guide it it doesn't work on Emunand.

**Comment by DimitriDokuchaev** [comment]
Abastante Why are you so keen on running that on Emunand, just update your setup and follow the guide Margen67 posted.

**Comment by crazc** [comment]
Upgrading to A9LH or pretty much just anything not EmuNAND would allow you to use this.

**Comment by Abastante** [comment]
LOL Don't judge me guys. I'm just afraid of losing my games progress and shit. I mean, my console works perfectly on Emunand and just going through all that pain to play NDS games doesn't seem to worth the trouble. I donno.

**Comment by crazc** [comment]
Part of the process of installing A9LH involves backing up your game saves, and every game you have installed currently can be installed again.

**Comment by cheuble** [comment]
If you know how to read a guide, you'll not brick, keep your saves, and enjoy A9LH's features! @Abastante

**Comment by DimitriDokuchaev** [comment]
You won't lose anything if you read the guide correctly @Abastante , read it once make sure you understand the steps before doing it, it's so really simple, just follow the bullet instructions.

**Comment by TheKingy34** [comment]
@Abastante: >Loosing progress and shit
It's _**SUPER, SUPER**_ simple to use the guide, this is how to be 100% safe using the guide:
1. Read.
It's super simple, I've done it like 4-5 times and I haven't lost anything

**Comment by Margen67** [comment]
You can, but you shouldn't. EmuNAND is a waste of time, and space unless you're using it for:
Getting around the title limit (~300)
Region change
NAND experiments/development

Gateway can be launched as a payload on A9LH.
the only useful thing Gateway provides is more convenient cheats.
The cheats can be converted for use in NTR and 3ds/3dz roms can be converted to CIA.
Which is more convenient anyways since it will be on your home menu without going through any interfaces, and is also usable in Luma.

The problem with non-A9LH/K9LH entrypoints is if you take out the SD card, or get on the SysNAND without protection you can potentially update to a firmware without any exploits.
11.2 is the latest firmware as of writing this which is exploitable BUT eventually a new firmware will be released, and it won't be exploitable.
Non-A9LH/K9LH entrypoints also have <100% boot rate and take longer to boot.
You will also have to install GBA/DSiWare twice for it to work properly.


If you're still not convinced please do some research, and come back once you have.
You will find that most, if not all bricks are caused by user error (partially OTPless which isn't used anymore) not random failures within the software.
If the bricks were proven to not be user error then 3ds.guide wouldn't have you install A9LH.
Do you really think someone would make a comprehensive, multilingual guide for something that just bricks your 3DS?

AND if you're still not convinced ask anyone on a 3DS hacking chat, message board, etc. They will also say bricks are caused by user error.
If you don't think what a random user says is relevant then you can ask a developer like Aurora Wright, TuxSH, etc.

**Comment by pbanj** [comment]
https://3ds.guide/move-emunand holy shit look at that you can move your emunand to your sysnand and keep everything. it's almost like the guide thought of users who already had a set up before a9lh.

**Comment by Abastante** [comment]
Thank you guys!! You gave me the courage to give this a try. I'm totally confident that I can go through this. It just that I didn't think it was worth it but I've been checking out some vids and I like how fast it boots and all that shit. 
I'll let you know the outcome!

**Comment by pbanj** [comment]
for the love of god do NOT follow a god damn video guide.

**Comment by Abastante** [comment]
hahahah I won't. I'll stick to the guide you guys gave me. I'm experienced following these guides. I've been installing CFW on consoles since the PSP time, but as I got older I started losing interest on getting the LATEST one and I only do this shit when cornered. But in this case, I'll do it to feel young again wiii.

**Comment by Abastante** [comment]
All right guys! I frikin did it! Thanks so much for your help. Mario64 is working now and my console is better than ever. 
Thanks for pushing me into this :D

**Comment by Margen67** [comment]
@Robz8 @Abastante You can close this now. It's been solved.
